-- ODIN database schema
-- All primary keys are UUIDs (TEXT), generated by the application.
-- Sync columns on every table: created_at, updated_at, created_by, updated_by.

PRAGMA journal_mode = WAL;
PRAGMA foreign_keys = ON;

-- ─────────────────────────────────────────────────────────────────────────────
-- lookup_values
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS lookup_values (
    id            TEXT PRIMARY KEY,
    list          TEXT NOT NULL,
    code          TEXT NOT NULL,
    description   TEXT,
    external_code TEXT,   -- canonical code used by external systems, e.g. ONT kit name "SQK-RBK114-24"
    -- sync columns
    created_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    created_by    TEXT,
    updated_by    TEXT,
    UNIQUE (list, code)
);

-- ─────────────────────────────────────────────────────────────────────────────
-- config_values
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS config_values (
    id          TEXT PRIMARY KEY,
    key         TEXT NOT NULL UNIQUE,
    value       TEXT,
    -- sync columns
    created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    created_by  TEXT,
    updated_by  TEXT
);

-- ─────────────────────────────────────────────────────────────────────────────
-- databases
--   Entries for the taxprofiler --databases CSV.
--   db_path is stored in Git Bash format (/d/path) via normalize_for_storage,
--   and coerced to the runtime environment format at launch time.
--   Pure WSL paths (/home/...) pass through normalize_for_storage unchanged
--   and are correct for WSL execution as-is.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS databases (
    id          TEXT PRIMARY KEY,
    tool        TEXT NOT NULL,      -- e.g. kraken2, diamond
    db_name     TEXT NOT NULL,      -- arbitrary label
    db_params   TEXT,               -- extra CLI flags, e.g. --quick
    db_path     TEXT NOT NULL,      -- path in Git Bash / WSL format
    -- sync columns
    created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    created_by  TEXT,
    updated_by  TEXT,
    UNIQUE (tool, db_name)
);

-- ─────────────────────────────────────────────────────────────────────────────
-- sites
-- ─────────────────────────────────────────────────────────────────────────────
-- site_code looks like a derived column with nullable inputs, but it cannot be constrained
-- as one. Two tested behaviours prevent it: the API deliberately derives from a *partial* set
-- ("derived site_code uses whatever components are provided" —
-- test_sites.py::test_create_partial_components_uses_available), and the Excel import supplies
-- site_code *verbatim* with no components at all (test_import_replace_mode_deletes_unseen_sites
-- imports a sheet of just site_code + country). So even "at least one component is present" is
-- false by design. See §J in the plan doc — tightening this is a product decision, not a
-- schema-mechanics one.
CREATE TABLE IF NOT EXISTS sites (
    id           TEXT PRIMARY KEY,
    site_code    TEXT NOT NULL UNIQUE,
    site         TEXT,
    country      TEXT NOT NULL,
    country_code TEXT,
    city_code    TEXT,
    city         TEXT,
    location     TEXT,
    longitude    REAL,
    latitude     REAL,
    comments     TEXT,
    -- sync columns
    created_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    created_by   TEXT,
    updated_by   TEXT
);

-- ─────────────────────────────────────────────────────────────────────────────
-- samples
-- ─────────────────────────────────────────────────────────────────────────────
-- sample_code is derived from site_id + sample_type, and BOTH are NOT NULL so the derived
-- value is always meaningful. That matters because sample_code is half of the sync merge key
-- (UNIQUE (sample_code, sampling_date)): a sample whose code could not be derived correctly
-- yields a garbage key that collides or duplicates across devices.
--
-- This was DECIDED (2026-07-30), not discovered — the Excel import previously created a
-- sample whose site_code did not resolve, so the invariant was not true before. Import now
-- skips such a row and counts it in summary.samples.skipped, matching what seed_samples
-- already did ("rows with no matching site are skipped"). See §J in the plan doc.
--
-- Contrast nanopore_runs.sample_id and biomeme_runs.sample_id, which stay nullable because
-- "unlinked" is a supported state there, and sites' own components, which stay nullable
-- because partial sites are supported and import supplies site_code verbatim.
CREATE TABLE IF NOT EXISTS samples (
    id                       TEXT PRIMARY KEY,
    sample_code              TEXT NOT NULL,
    site_id                  TEXT NOT NULL REFERENCES sites(id),
    sample_type              TEXT NOT NULL,
    depth                    TEXT,
    elevation                TEXT,
    sampling_date            TEXT NOT NULL
        CHECK (sampling_date GLOB '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'),
    comments_sampling        TEXT,
    partner_sample_code      TEXT,
    -- NULL-tolerant: extraction may not have happened yet.
    date_extraction          TEXT
        CHECK (date_extraction IS NULL
               OR date_extraction GLOB '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'),
    nucleic_acid_concentration TEXT,
    extract_volume           TEXT,
    comments_extraction      TEXT,
    elution_volume           TEXT,
    comments                 TEXT,
    -- sync columns
    created_at               TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at               TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    created_by               TEXT,
    updated_by               TEXT,
    UNIQUE (sample_code, sampling_date)
);

-- ─────────────────────────────────────────────────────────────────────────────
-- nanopore_run_accessions  (run-level metadata; one row per sequencing run)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS nanopore_run_accessions (
    id                  TEXT PRIMARY KEY,          -- UUID; stable from creation
    run_accession       TEXT UNIQUE,               -- nullable; set after run starts
    label               TEXT UNIQUE,               -- human-readable tag; required when run_accession IS NULL
    protocol_id         TEXT,
    sequencing_kit_id   TEXT,
    runName             TEXT,
    sampleName          TEXT,
    comments            TEXT,
    -- sync columns
    created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    created_by  TEXT,
    updated_by  TEXT,
    CHECK (run_accession IS NOT NULL OR label IS NOT NULL)
);

-- ─────────────────────────────────────────────────────────────────────────────
-- nanopore_disk_cache  (auto-populated on every disk scan; no user data)
--   Populated by discover_nanopore() for every run folder found on disk.
--   Evicted for folders that have been removed since the last scan.
--   Never written by user-facing registration endpoints.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS nanopore_disk_cache (
    run_accession     TEXT PRIMARY KEY,
    flow_cell_id      TEXT,
    run_started       TEXT,   -- ISO-8601 from final_summary_*.txt or folder name
    run_stopped       TEXT,   -- ISO-8601 from final_summary_*.txt
    sequencing_kit_id TEXT,   -- extracted from protocol string in final_summary_*.txt
    run_name          TEXT,   -- protocol_group_id (experiment name) from final_summary
    scanned_at        TEXT NOT NULL
);

-- ─────────────────────────────────────────────────────────────────────────────
-- nanopore_runs
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS nanopore_runs (
    id                  TEXT PRIMARY KEY,
    accession_id        TEXT NOT NULL REFERENCES nanopore_run_accessions(id),
    sample_id           TEXT REFERENCES samples(id),
    barcode             TEXT NOT NULL,
    type                TEXT,          -- mpox barcode type (test_sample, positive_control, negative_control, no_template_control)
    -- sync columns
    created_at          TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at          TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    created_by          TEXT,
    updated_by          TEXT,
    UNIQUE (accession_id, barcode)
);

-- ─────────────────────────────────────────────────────────────────────────────
-- biomeme_runs
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS biomeme_runs (
    id                TEXT PRIMARY KEY,
    biomeme_run_name  TEXT NOT NULL UNIQUE,
    sample_id         TEXT REFERENCES samples(id),
    biomeme_sample_id TEXT,
    dilution_factor   REAL,
    comments          TEXT,
    -- sync columns
    created_at        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    created_by        TEXT,
    updated_by        TEXT
);

-- ─────────────────────────────────────────────────────────────────────────────
-- nanopore_run_exclusions  (local-only: runs the user wants to hide from processing)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS nanopore_run_exclusions (
    run_accession  TEXT PRIMARY KEY,
    reason         TEXT,
    created_at     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    created_by     TEXT
);

-- ─────────────────────────────────────────────────────────────────────────────
-- biomeme_folder_exclusions  (local-only: biomeme disk folders to hide from processing)
-- Key is the folder_path, e.g. "DC/20250915"
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS biomeme_folder_exclusions (
    folder_path  TEXT PRIMARY KEY,
    reason       TEXT,
    created_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    created_by   TEXT
);

-- ─────────────────────────────────────────────────────────────────────────────
-- nanopore_barcode_exclusions  (local-only: individual barcodes to skip)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS nanopore_barcode_exclusions (
    run_accession  TEXT NOT NULL,
    barcode        TEXT NOT NULL,
    reason         TEXT,
    created_at     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    created_by     TEXT,
    PRIMARY KEY (run_accession, barcode)
);

-- ─────────────────────────────────────────────────────────────────────────────
-- nanopore_merge_decisions  (local-only: user's per-run merge choice)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS nanopore_merge_decisions (
    run_accession     TEXT PRIMARY KEY,
    auto_merge        INTEGER NOT NULL DEFAULT 0,  -- 1 = merge with related runs, 0 = this run only
    related_snapshot  TEXT,                        -- JSON array of related run_accessions at decision time; NULL = predates this feature (treat as stale)
    created_at        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    created_by        TEXT
);

-- ─────────────────────────────────────────────────────────────────────────────
-- pipeline_runs  (local-only: tracks background pipeline jobs, not synced)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS pipeline_runs (
    id              TEXT PRIMARY KEY,
    pipeline_type   TEXT NOT NULL,   -- taxprofiler | wf_metagenomics_amr | wf_metagenomics_ssu | mpox
    status          TEXT NOT NULL DEFAULT 'queued',   -- queued | running | done | failed | cancelled
    params          TEXT,            -- JSON: pipeline-specific params (clade, database_set, etc.)
    pid             INTEGER,         -- OS process ID while running
    log_file        TEXT,            -- absolute path to the captured log file
    exit_code       INTEGER,
    started_at      TEXT,
    finished_at     TEXT,
    output_path     TEXT,
    work_dir        TEXT,
    created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    created_by      TEXT
);

-- ─────────────────────────────────────────────────────────────────────────────
-- pipeline_run_accessions  (junction: pipeline_runs → nanopore_run_accessions)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS pipeline_run_accessions (
    pipeline_run_id  TEXT NOT NULL REFERENCES pipeline_runs(id) ON DELETE CASCADE,
    run_accession    TEXT NOT NULL,
    PRIMARY KEY (pipeline_run_id, run_accession)
);
